apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app.name}}-service
  namespace: default
  labels:
    app: {{.Values.app.name}}-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    port: {{.Values.service.https.port}}
    protocol: TCP
    targetPort: {{.Values.service.targetPort}}
  - name: http
    port: {{.Values.service.http.port}}
    protocol: TCP
    targetPort: {{.Values.service.targetPort}}
  selector:
    app: {{.Values.app.name}}
  type: LoadBalancer